### ISSUE TITLE
Issues with Sockets

### ISSUE THREAD

**Issue by sugarcanefarmer** [Genteki/pyvts#42]
Hey there, I am having issues with the sockets on Windows 11. I recently transferred a project from one PC to another, the previous one being Windows 10, and the new one being 11. After setting up the venv and all that again, I get a new issue. I tried backdating the websockets install; but it didn't do anything. It's running the same version of pyvts as before, too. The only change is a new PC. Obviously, the "Remote Computer" in this given error is not remote, but the same PC. I have no strange anti-virus or anything that I could imagine would block ports; just a bog standard Windows 11 Pro install. The error happens when running to attempt and create the connection; this happens on script startup.

python=3.11.6
websockets=11.0.3
pyvts=0.3.1

It keeps giving me this full error log:

> Exception in thread Thread-3 (run_vtube_studio_connection):
Traceback (most recent call last):
  File "C:\Users\Michola\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "C:\Users\Michola\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "C:\MiquellaMain\Waifu-master\utils\vtube_studio.py", line 33, in run_vtube_studio_connection
    asyncio.run(vtube_studio_connection())
  File "C:\Users\Michola\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Michola\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michola\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\MiquellaMain\Waifu-master\utils\vtube_studio.py", line 36, in vtube_studio_connection
    await VTS.connect()
  File "C:\MiquellaMain\Waifu-master\venv\Lib\site-packages\pyvts\vts.py", line 70, in connect
    self.websocket = await websockets.connect(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\MiquellaMain\Waifu-master\venv\Lib\site-packages\websockets\legacy\client.py", line 655, in __await_impl_timeout__
    return await self.__await_impl__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\MiquellaMain\Waifu-master\venv\Lib\site-packages\websockets\legacy\client.py", line 659, in __await_impl__
    _transport, _protocol = await self._create_connection()
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michola\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1090, in create_connection
    raise exceptions[0]
  File "C:\Users\Michola\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1069, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michola\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 973, in _connect_sock
    await self.sock_connect(sock, address)
  File "C:\Users\Michola\AppData\Local\Programs\Python\Python311\Lib\asyncio\proactor_events.py", line 726, in sock_connect
    return await self._proactor.connect(sock, address)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michola\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 846, in _poll
    value = callback(transferred, key, ov)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michola\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 633, in finish_connect
    ov.getresult()
ConnectionRefusedError: [WinError 1225] The remote computer refused the network connection

**Comment by sugarcanefarmer** [comment]
I... was being dumb. I forgot I had to turn on the VTube Studio API after I installed it on the new computer. Turned it on in the menus, worked first try.

No issues now. If anyone in the future gets this "ConnectionRefusedError: [WinError 1225] The remote computer refused the network connection", you need to turn on the API in VTube Studio, as there is no open socket to send it to otherwise lol.
